//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yqun.BO.BusinessManager.EMCServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PressureData", Namespace="http://schemas.datacontract.org/2004/07/DataInterfaceSln")]
    [System.SerializableAttribute()]
    public partial class PressureData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIswjjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FKylzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FLqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FQddjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FRtcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSbbhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSjbhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FSjccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSoftcomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSysjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FVenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FWtbhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FYskylzField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FGuid {
            get {
                return this.FGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.FGuidField, value) != true)) {
                    this.FGuidField = value;
                    this.RaisePropertyChanged("FGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIswjj {
            get {
                return this.FIswjjField;
            }
            set {
                if ((object.ReferenceEquals(this.FIswjjField, value) != true)) {
                    this.FIswjjField = value;
                    this.RaisePropertyChanged("FIswjj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FKylz {
            get {
                return this.FKylzField;
            }
            set {
                if ((this.FKylzField.Equals(value) != true)) {
                    this.FKylzField = value;
                    this.RaisePropertyChanged("FKylz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FLq {
            get {
                return this.FLqField;
            }
            set {
                if ((this.FLqField.Equals(value) != true)) {
                    this.FLqField = value;
                    this.RaisePropertyChanged("FLq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FOperator {
            get {
                return this.FOperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.FOperatorField, value) != true)) {
                    this.FOperatorField = value;
                    this.RaisePropertyChanged("FOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FQddj {
            get {
                return this.FQddjField;
            }
            set {
                if ((object.ReferenceEquals(this.FQddjField, value) != true)) {
                    this.FQddjField = value;
                    this.RaisePropertyChanged("FQddj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FRtcode {
            get {
                return this.FRtcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FRtcodeField, value) != true)) {
                    this.FRtcodeField = value;
                    this.RaisePropertyChanged("FRtcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSbbh {
            get {
                return this.FSbbhField;
            }
            set {
                if ((object.ReferenceEquals(this.FSbbhField, value) != true)) {
                    this.FSbbhField = value;
                    this.RaisePropertyChanged("FSbbh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSjbh {
            get {
                return this.FSjbhField;
            }
            set {
                if ((object.ReferenceEquals(this.FSjbhField, value) != true)) {
                    this.FSjbhField = value;
                    this.RaisePropertyChanged("FSjbh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FSjcc {
            get {
                return this.FSjccField;
            }
            set {
                if ((this.FSjccField.Equals(value) != true)) {
                    this.FSjccField = value;
                    this.RaisePropertyChanged("FSjcc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSoftcom {
            get {
                return this.FSoftcomField;
            }
            set {
                if ((object.ReferenceEquals(this.FSoftcomField, value) != true)) {
                    this.FSoftcomField = value;
                    this.RaisePropertyChanged("FSoftcom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSysj {
            get {
                return this.FSysjField;
            }
            set {
                if ((object.ReferenceEquals(this.FSysjField, value) != true)) {
                    this.FSysjField = value;
                    this.RaisePropertyChanged("FSysj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FVender {
            get {
                return this.FVenderField;
            }
            set {
                if ((object.ReferenceEquals(this.FVenderField, value) != true)) {
                    this.FVenderField = value;
                    this.RaisePropertyChanged("FVender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FWtbh {
            get {
                return this.FWtbhField;
            }
            set {
                if ((object.ReferenceEquals(this.FWtbhField, value) != true)) {
                    this.FWtbhField = value;
                    this.RaisePropertyChanged("FWtbh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FYskylz {
            get {
                return this.FYskylzField;
            }
            set {
                if ((object.ReferenceEquals(this.FYskylzField, value) != true)) {
                    this.FYskylzField = value;
                    this.RaisePropertyChanged("FYskylz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversalData", Namespace="http://schemas.datacontract.org/2004/07/DataInterfaceSln")]
    [System.SerializableAttribute()]
    public partial class UniversalData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FGczjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FLzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FPzcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FQflzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FRtcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSbbhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FSclField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSjbhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSoftcomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSysjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FVenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FWtbhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FWyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FYskllzField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FArea {
            get {
                return this.FAreaField;
            }
            set {
                if ((this.FAreaField.Equals(value) != true)) {
                    this.FAreaField = value;
                    this.RaisePropertyChanged("FArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FGczj {
            get {
                return this.FGczjField;
            }
            set {
                if ((this.FGczjField.Equals(value) != true)) {
                    this.FGczjField = value;
                    this.RaisePropertyChanged("FGczj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FGuid {
            get {
                return this.FGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.FGuidField, value) != true)) {
                    this.FGuidField = value;
                    this.RaisePropertyChanged("FGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FLz {
            get {
                return this.FLzField;
            }
            set {
                if ((this.FLzField.Equals(value) != true)) {
                    this.FLzField = value;
                    this.RaisePropertyChanged("FLz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FOperator {
            get {
                return this.FOperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.FOperatorField, value) != true)) {
                    this.FOperatorField = value;
                    this.RaisePropertyChanged("FOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FPzcode {
            get {
                return this.FPzcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FPzcodeField, value) != true)) {
                    this.FPzcodeField = value;
                    this.RaisePropertyChanged("FPzcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FQflz {
            get {
                return this.FQflzField;
            }
            set {
                if ((this.FQflzField.Equals(value) != true)) {
                    this.FQflzField = value;
                    this.RaisePropertyChanged("FQflz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FRtcode {
            get {
                return this.FRtcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FRtcodeField, value) != true)) {
                    this.FRtcodeField = value;
                    this.RaisePropertyChanged("FRtcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSbbh {
            get {
                return this.FSbbhField;
            }
            set {
                if ((object.ReferenceEquals(this.FSbbhField, value) != true)) {
                    this.FSbbhField = value;
                    this.RaisePropertyChanged("FSbbh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FScl {
            get {
                return this.FSclField;
            }
            set {
                if ((this.FSclField.Equals(value) != true)) {
                    this.FSclField = value;
                    this.RaisePropertyChanged("FScl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSjbh {
            get {
                return this.FSjbhField;
            }
            set {
                if ((object.ReferenceEquals(this.FSjbhField, value) != true)) {
                    this.FSjbhField = value;
                    this.RaisePropertyChanged("FSjbh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSoftcom {
            get {
                return this.FSoftcomField;
            }
            set {
                if ((object.ReferenceEquals(this.FSoftcomField, value) != true)) {
                    this.FSoftcomField = value;
                    this.RaisePropertyChanged("FSoftcom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSysj {
            get {
                return this.FSysjField;
            }
            set {
                if ((object.ReferenceEquals(this.FSysjField, value) != true)) {
                    this.FSysjField = value;
                    this.RaisePropertyChanged("FSysj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FVender {
            get {
                return this.FVenderField;
            }
            set {
                if ((object.ReferenceEquals(this.FVenderField, value) != true)) {
                    this.FVenderField = value;
                    this.RaisePropertyChanged("FVender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FWtbh {
            get {
                return this.FWtbhField;
            }
            set {
                if ((object.ReferenceEquals(this.FWtbhField, value) != true)) {
                    this.FWtbhField = value;
                    this.RaisePropertyChanged("FWtbh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FWy {
            get {
                return this.FWyField;
            }
            set {
                if ((object.ReferenceEquals(this.FWyField, value) != true)) {
                    this.FWyField = value;
                    this.RaisePropertyChanged("FWy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FYskllz {
            get {
                return this.FYskllzField;
            }
            set {
                if ((object.ReferenceEquals(this.FYskllzField, value) != true)) {
                    this.FYskllzField = value;
                    this.RaisePropertyChanged("FYskllz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MixmachineData", Namespace="http://schemas.datacontract.org/2004/07/DataInterfaceSln")]
    [System.SerializableAttribute()]
    public partial class MixmachineData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FBaocunshijianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FBhjcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FCaozuozheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FChuliaoshijianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FFangliangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FFenliao5LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FFenliao5ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FFenliao6LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FFenliao6ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FFenmeihuiLilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FFenmeihuiShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FGongchengmingchengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FGongdanhaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FJiaobanshijianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FJiaozhubuweiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FKehuduanbianhaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FKuangfenLilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FKuangfenShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FPeifanghaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FQiangdudengjiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FSha1LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FSha1ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FSha2LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FSha2ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShejifangliangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShi1LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShi1ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShi2LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShi2ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShi3LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShi3ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FShigongdidianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShui1LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShui1ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShui2LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShui2ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShuini1LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShuini1ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShuini2LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FShuini2ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FShuinipinzhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FVenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FWaijiaji1LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FWaijiaji1ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FWaijiaji2LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FWaijiaji2ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FWaijiaji3LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FWaijiaji3ShijizhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FWaijiaji4LilunzhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FWaijiaji4ShijizhiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBaocunshijian {
            get {
                return this.FBaocunshijianField;
            }
            set {
                if ((object.ReferenceEquals(this.FBaocunshijianField, value) != true)) {
                    this.FBaocunshijianField = value;
                    this.RaisePropertyChanged("FBaocunshijian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBhjcode {
            get {
                return this.FBhjcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FBhjcodeField, value) != true)) {
                    this.FBhjcodeField = value;
                    this.RaisePropertyChanged("FBhjcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FCaozuozhe {
            get {
                return this.FCaozuozheField;
            }
            set {
                if ((object.ReferenceEquals(this.FCaozuozheField, value) != true)) {
                    this.FCaozuozheField = value;
                    this.RaisePropertyChanged("FCaozuozhe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FChuliaoshijian {
            get {
                return this.FChuliaoshijianField;
            }
            set {
                if ((object.ReferenceEquals(this.FChuliaoshijianField, value) != true)) {
                    this.FChuliaoshijianField = value;
                    this.RaisePropertyChanged("FChuliaoshijian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FFangliang {
            get {
                return this.FFangliangField;
            }
            set {
                if ((this.FFangliangField.Equals(value) != true)) {
                    this.FFangliangField = value;
                    this.RaisePropertyChanged("FFangliang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FFenliao5Lilunzhi {
            get {
                return this.FFenliao5LilunzhiField;
            }
            set {
                if ((this.FFenliao5LilunzhiField.Equals(value) != true)) {
                    this.FFenliao5LilunzhiField = value;
                    this.RaisePropertyChanged("FFenliao5Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FFenliao5Shijizhi {
            get {
                return this.FFenliao5ShijizhiField;
            }
            set {
                if ((this.FFenliao5ShijizhiField.Equals(value) != true)) {
                    this.FFenliao5ShijizhiField = value;
                    this.RaisePropertyChanged("FFenliao5Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FFenliao6Lilunzhi {
            get {
                return this.FFenliao6LilunzhiField;
            }
            set {
                if ((this.FFenliao6LilunzhiField.Equals(value) != true)) {
                    this.FFenliao6LilunzhiField = value;
                    this.RaisePropertyChanged("FFenliao6Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FFenliao6Shijizhi {
            get {
                return this.FFenliao6ShijizhiField;
            }
            set {
                if ((this.FFenliao6ShijizhiField.Equals(value) != true)) {
                    this.FFenliao6ShijizhiField = value;
                    this.RaisePropertyChanged("FFenliao6Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FFenmeihuiLilunzhi {
            get {
                return this.FFenmeihuiLilunzhiField;
            }
            set {
                if ((this.FFenmeihuiLilunzhiField.Equals(value) != true)) {
                    this.FFenmeihuiLilunzhiField = value;
                    this.RaisePropertyChanged("FFenmeihuiLilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FFenmeihuiShijizhi {
            get {
                return this.FFenmeihuiShijizhiField;
            }
            set {
                if ((this.FFenmeihuiShijizhiField.Equals(value) != true)) {
                    this.FFenmeihuiShijizhiField = value;
                    this.RaisePropertyChanged("FFenmeihuiShijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FGongchengmingcheng {
            get {
                return this.FGongchengmingchengField;
            }
            set {
                if ((object.ReferenceEquals(this.FGongchengmingchengField, value) != true)) {
                    this.FGongchengmingchengField = value;
                    this.RaisePropertyChanged("FGongchengmingcheng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FGongdanhao {
            get {
                return this.FGongdanhaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FGongdanhaoField, value) != true)) {
                    this.FGongdanhaoField = value;
                    this.RaisePropertyChanged("FGongdanhao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FJiaobanshijian {
            get {
                return this.FJiaobanshijianField;
            }
            set {
                if ((this.FJiaobanshijianField.Equals(value) != true)) {
                    this.FJiaobanshijianField = value;
                    this.RaisePropertyChanged("FJiaobanshijian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FJiaozhubuwei {
            get {
                return this.FJiaozhubuweiField;
            }
            set {
                if ((object.ReferenceEquals(this.FJiaozhubuweiField, value) != true)) {
                    this.FJiaozhubuweiField = value;
                    this.RaisePropertyChanged("FJiaozhubuwei");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FKehuduanbianhao {
            get {
                return this.FKehuduanbianhaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FKehuduanbianhaoField, value) != true)) {
                    this.FKehuduanbianhaoField = value;
                    this.RaisePropertyChanged("FKehuduanbianhao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FKuangfenLilunzhi {
            get {
                return this.FKuangfenLilunzhiField;
            }
            set {
                if ((this.FKuangfenLilunzhiField.Equals(value) != true)) {
                    this.FKuangfenLilunzhiField = value;
                    this.RaisePropertyChanged("FKuangfenLilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FKuangfenShijizhi {
            get {
                return this.FKuangfenShijizhiField;
            }
            set {
                if ((this.FKuangfenShijizhiField.Equals(value) != true)) {
                    this.FKuangfenShijizhiField = value;
                    this.RaisePropertyChanged("FKuangfenShijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FPeifanghao {
            get {
                return this.FPeifanghaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FPeifanghaoField, value) != true)) {
                    this.FPeifanghaoField = value;
                    this.RaisePropertyChanged("FPeifanghao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FQiangdudengji {
            get {
                return this.FQiangdudengjiField;
            }
            set {
                if ((object.ReferenceEquals(this.FQiangdudengjiField, value) != true)) {
                    this.FQiangdudengjiField = value;
                    this.RaisePropertyChanged("FQiangdudengji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FSha1Lilunzhi {
            get {
                return this.FSha1LilunzhiField;
            }
            set {
                if ((this.FSha1LilunzhiField.Equals(value) != true)) {
                    this.FSha1LilunzhiField = value;
                    this.RaisePropertyChanged("FSha1Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FSha1Shijizhi {
            get {
                return this.FSha1ShijizhiField;
            }
            set {
                if ((this.FSha1ShijizhiField.Equals(value) != true)) {
                    this.FSha1ShijizhiField = value;
                    this.RaisePropertyChanged("FSha1Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FSha2Lilunzhi {
            get {
                return this.FSha2LilunzhiField;
            }
            set {
                if ((this.FSha2LilunzhiField.Equals(value) != true)) {
                    this.FSha2LilunzhiField = value;
                    this.RaisePropertyChanged("FSha2Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FSha2Shijizhi {
            get {
                return this.FSha2ShijizhiField;
            }
            set {
                if ((this.FSha2ShijizhiField.Equals(value) != true)) {
                    this.FSha2ShijizhiField = value;
                    this.RaisePropertyChanged("FSha2Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShejifangliang {
            get {
                return this.FShejifangliangField;
            }
            set {
                if ((this.FShejifangliangField.Equals(value) != true)) {
                    this.FShejifangliangField = value;
                    this.RaisePropertyChanged("FShejifangliang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShi1Lilunzhi {
            get {
                return this.FShi1LilunzhiField;
            }
            set {
                if ((this.FShi1LilunzhiField.Equals(value) != true)) {
                    this.FShi1LilunzhiField = value;
                    this.RaisePropertyChanged("FShi1Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShi1Shijizhi {
            get {
                return this.FShi1ShijizhiField;
            }
            set {
                if ((this.FShi1ShijizhiField.Equals(value) != true)) {
                    this.FShi1ShijizhiField = value;
                    this.RaisePropertyChanged("FShi1Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShi2Lilunzhi {
            get {
                return this.FShi2LilunzhiField;
            }
            set {
                if ((this.FShi2LilunzhiField.Equals(value) != true)) {
                    this.FShi2LilunzhiField = value;
                    this.RaisePropertyChanged("FShi2Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShi2Shijizhi {
            get {
                return this.FShi2ShijizhiField;
            }
            set {
                if ((this.FShi2ShijizhiField.Equals(value) != true)) {
                    this.FShi2ShijizhiField = value;
                    this.RaisePropertyChanged("FShi2Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShi3Lilunzhi {
            get {
                return this.FShi3LilunzhiField;
            }
            set {
                if ((this.FShi3LilunzhiField.Equals(value) != true)) {
                    this.FShi3LilunzhiField = value;
                    this.RaisePropertyChanged("FShi3Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShi3Shijizhi {
            get {
                return this.FShi3ShijizhiField;
            }
            set {
                if ((this.FShi3ShijizhiField.Equals(value) != true)) {
                    this.FShi3ShijizhiField = value;
                    this.RaisePropertyChanged("FShi3Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FShigongdidian {
            get {
                return this.FShigongdidianField;
            }
            set {
                if ((object.ReferenceEquals(this.FShigongdidianField, value) != true)) {
                    this.FShigongdidianField = value;
                    this.RaisePropertyChanged("FShigongdidian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShui1Lilunzhi {
            get {
                return this.FShui1LilunzhiField;
            }
            set {
                if ((this.FShui1LilunzhiField.Equals(value) != true)) {
                    this.FShui1LilunzhiField = value;
                    this.RaisePropertyChanged("FShui1Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShui1Shijizhi {
            get {
                return this.FShui1ShijizhiField;
            }
            set {
                if ((this.FShui1ShijizhiField.Equals(value) != true)) {
                    this.FShui1ShijizhiField = value;
                    this.RaisePropertyChanged("FShui1Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShui2Lilunzhi {
            get {
                return this.FShui2LilunzhiField;
            }
            set {
                if ((this.FShui2LilunzhiField.Equals(value) != true)) {
                    this.FShui2LilunzhiField = value;
                    this.RaisePropertyChanged("FShui2Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShui2Shijizhi {
            get {
                return this.FShui2ShijizhiField;
            }
            set {
                if ((this.FShui2ShijizhiField.Equals(value) != true)) {
                    this.FShui2ShijizhiField = value;
                    this.RaisePropertyChanged("FShui2Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShuini1Lilunzhi {
            get {
                return this.FShuini1LilunzhiField;
            }
            set {
                if ((this.FShuini1LilunzhiField.Equals(value) != true)) {
                    this.FShuini1LilunzhiField = value;
                    this.RaisePropertyChanged("FShuini1Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShuini1Shijizhi {
            get {
                return this.FShuini1ShijizhiField;
            }
            set {
                if ((this.FShuini1ShijizhiField.Equals(value) != true)) {
                    this.FShuini1ShijizhiField = value;
                    this.RaisePropertyChanged("FShuini1Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShuini2Lilunzhi {
            get {
                return this.FShuini2LilunzhiField;
            }
            set {
                if ((this.FShuini2LilunzhiField.Equals(value) != true)) {
                    this.FShuini2LilunzhiField = value;
                    this.RaisePropertyChanged("FShuini2Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FShuini2Shijizhi {
            get {
                return this.FShuini2ShijizhiField;
            }
            set {
                if ((this.FShuini2ShijizhiField.Equals(value) != true)) {
                    this.FShuini2ShijizhiField = value;
                    this.RaisePropertyChanged("FShuini2Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FShuinipinzhong {
            get {
                return this.FShuinipinzhongField;
            }
            set {
                if ((object.ReferenceEquals(this.FShuinipinzhongField, value) != true)) {
                    this.FShuinipinzhongField = value;
                    this.RaisePropertyChanged("FShuinipinzhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FVender {
            get {
                return this.FVenderField;
            }
            set {
                if ((object.ReferenceEquals(this.FVenderField, value) != true)) {
                    this.FVenderField = value;
                    this.RaisePropertyChanged("FVender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FWaijiaji1Lilunzhi {
            get {
                return this.FWaijiaji1LilunzhiField;
            }
            set {
                if ((this.FWaijiaji1LilunzhiField.Equals(value) != true)) {
                    this.FWaijiaji1LilunzhiField = value;
                    this.RaisePropertyChanged("FWaijiaji1Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FWaijiaji1Shijizhi {
            get {
                return this.FWaijiaji1ShijizhiField;
            }
            set {
                if ((this.FWaijiaji1ShijizhiField.Equals(value) != true)) {
                    this.FWaijiaji1ShijizhiField = value;
                    this.RaisePropertyChanged("FWaijiaji1Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FWaijiaji2Lilunzhi {
            get {
                return this.FWaijiaji2LilunzhiField;
            }
            set {
                if ((this.FWaijiaji2LilunzhiField.Equals(value) != true)) {
                    this.FWaijiaji2LilunzhiField = value;
                    this.RaisePropertyChanged("FWaijiaji2Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FWaijiaji2Shijizhi {
            get {
                return this.FWaijiaji2ShijizhiField;
            }
            set {
                if ((this.FWaijiaji2ShijizhiField.Equals(value) != true)) {
                    this.FWaijiaji2ShijizhiField = value;
                    this.RaisePropertyChanged("FWaijiaji2Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FWaijiaji3Lilunzhi {
            get {
                return this.FWaijiaji3LilunzhiField;
            }
            set {
                if ((this.FWaijiaji3LilunzhiField.Equals(value) != true)) {
                    this.FWaijiaji3LilunzhiField = value;
                    this.RaisePropertyChanged("FWaijiaji3Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FWaijiaji3Shijizhi {
            get {
                return this.FWaijiaji3ShijizhiField;
            }
            set {
                if ((this.FWaijiaji3ShijizhiField.Equals(value) != true)) {
                    this.FWaijiaji3ShijizhiField = value;
                    this.RaisePropertyChanged("FWaijiaji3Shijizhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FWaijiaji4Lilunzhi {
            get {
                return this.FWaijiaji4LilunzhiField;
            }
            set {
                if ((this.FWaijiaji4LilunzhiField.Equals(value) != true)) {
                    this.FWaijiaji4LilunzhiField = value;
                    this.RaisePropertyChanged("FWaijiaji4Lilunzhi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FWaijiaji4Shijizhi {
            get {
                return this.FWaijiaji4ShijizhiField;
            }
            set {
                if ((this.FWaijiaji4ShijizhiField.Equals(value) != true)) {
                    this.FWaijiaji4ShijizhiField = value;
                    this.RaisePropertyChanged("FWaijiaji4Shijizhi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EMCServiceReference.IDataInterface")]
    public interface IDataInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataInterface/UploadPressureData", ReplyAction="http://tempuri.org/IDataInterface/UploadPressureDataResponse")]
        int UploadPressureData(out string errMsg, Yqun.BO.BusinessManager.EMCServiceReference.PressureData pressure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataInterface/UploadUniversalData", ReplyAction="http://tempuri.org/IDataInterface/UploadUniversalDataResponse")]
        int UploadUniversalData(out string errMsg, Yqun.BO.BusinessManager.EMCServiceReference.UniversalData universal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataInterface/UploadMixmachineData", ReplyAction="http://tempuri.org/IDataInterface/UploadMixmachineDataResponse")]
        int UploadMixmachineData(out string errMsg, Yqun.BO.BusinessManager.EMCServiceReference.MixmachineData universal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDataInterfaceChannel : Yqun.BO.BusinessManager.EMCServiceReference.IDataInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataInterfaceClient : System.ServiceModel.ClientBase<Yqun.BO.BusinessManager.EMCServiceReference.IDataInterface>, Yqun.BO.BusinessManager.EMCServiceReference.IDataInterface {
        
        public DataInterfaceClient() {
        }
        
        public DataInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UploadPressureData(out string errMsg, Yqun.BO.BusinessManager.EMCServiceReference.PressureData pressure) {
            return base.Channel.UploadPressureData(out errMsg, pressure);
        }
        
        public int UploadUniversalData(out string errMsg, Yqun.BO.BusinessManager.EMCServiceReference.UniversalData universal) {
            return base.Channel.UploadUniversalData(out errMsg, universal);
        }
        
        public int UploadMixmachineData(out string errMsg, Yqun.BO.BusinessManager.EMCServiceReference.MixmachineData universal) {
            return base.Channel.UploadMixmachineData(out errMsg, universal);
        }
    }
}
