//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yqun.BO.BusinessManager.GetDataFromEMC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDataFromEMC.IGetDataInterval")]
    public interface IGetDataInterval {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataInterval/GetBHZInfoData", ReplyAction="http://tempuri.org/IGetDataInterval/GetBHZInfoDataResponse")]
        int GetBHZInfoData(out string jsoBHZInfo, out string errMsg, string fvender, string xzbm, string beginTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataInterval/GetLabData", ReplyAction="http://tempuri.org/IGetDataInterval/GetLabDataResponse")]
        int GetLabData(out string jsoLabInfo, out string errMsg, string fvender, string xzbm, string beginTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataInterval/GetPressureData", ReplyAction="http://tempuri.org/IGetDataInterval/GetPressureDataResponse")]
        int GetPressureData(out string jsoPressureInfo, out string errMsg, string fvender, string xzbm, string f_wtbh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataInterval/GetUniversalData", ReplyAction="http://tempuri.org/IGetDataInterval/GetUniversalDataResponse")]
        int GetUniversalData(out string jsoUniversalInfo, out string errMsg, string fvender, string xzbm, string f_wtbh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IGetDataIntervalChannel : Yqun.BO.BusinessManager.GetDataFromEMC.IGetDataInterval, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetDataIntervalClient : System.ServiceModel.ClientBase<Yqun.BO.BusinessManager.GetDataFromEMC.IGetDataInterval>, Yqun.BO.BusinessManager.GetDataFromEMC.IGetDataInterval {
        
        public GetDataIntervalClient() {
        }
        
        public GetDataIntervalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataIntervalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataIntervalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataIntervalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetBHZInfoData(out string jsoBHZInfo, out string errMsg, string fvender, string xzbm, string beginTime, string endTime) {
            return base.Channel.GetBHZInfoData(out jsoBHZInfo, out errMsg, fvender, xzbm, beginTime, endTime);
        }
        
        public int GetLabData(out string jsoLabInfo, out string errMsg, string fvender, string xzbm, string beginTime, string endTime) {
            return base.Channel.GetLabData(out jsoLabInfo, out errMsg, fvender, xzbm, beginTime, endTime);
        }
        
        public int GetPressureData(out string jsoPressureInfo, out string errMsg, string fvender, string xzbm, string f_wtbh) {
            return base.Channel.GetPressureData(out jsoPressureInfo, out errMsg, fvender, xzbm, f_wtbh);
        }
        
        public int GetUniversalData(out string jsoUniversalInfo, out string errMsg, string fvender, string xzbm, string f_wtbh) {
            return base.Channel.GetUniversalData(out jsoUniversalInfo, out errMsg, fvender, xzbm, f_wtbh);
        }
    }
}
