//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataUploadWS.WLMQXinKeZhanSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WLMQXinKeZhanSR.IDataTransport")]
    public interface IDataTransport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransport/ReciveTestData", ReplyAction="http://tempuri.org/IDataTransport/ReciveTestDataResponse")]
        string ReciveTestData(byte[] testdata, string ksign, string jsdwCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDataTransportChannel : TestDataUploadWS.WLMQXinKeZhanSR.IDataTransport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataTransportClient : System.ServiceModel.ClientBase<TestDataUploadWS.WLMQXinKeZhanSR.IDataTransport>, TestDataUploadWS.WLMQXinKeZhanSR.IDataTransport {
        
        public DataTransportClient() {
        }
        
        public DataTransportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataTransportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTransportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTransportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReciveTestData(byte[] testdata, string ksign, string jsdwCode) {
            return base.Channel.ReciveTestData(testdata, ksign, jsdwCode);
        }
    }
}
