//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yqun.BO.BusinessManager.LabMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PressureData", Namespace="http://schemas.datacontract.org/2004/07/MixstationLibraryDMS.LabWCFService")]
    [System.SerializableAttribute()]
    public partial class PressureData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_COLCOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_ISWJJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float F_KYLZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int F_LQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_OPERATORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_QDDJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_RTCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SBCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SJBHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SJCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SOFTCOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SYSJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_WTBHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_YSKYLZField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_COLCOM {
            get {
                return this.F_COLCOMField;
            }
            set {
                if ((object.ReferenceEquals(this.F_COLCOMField, value) != true)) {
                    this.F_COLCOMField = value;
                    this.RaisePropertyChanged("F_COLCOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_GUID {
            get {
                return this.F_GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.F_GUIDField, value) != true)) {
                    this.F_GUIDField = value;
                    this.RaisePropertyChanged("F_GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_ISWJJ {
            get {
                return this.F_ISWJJField;
            }
            set {
                if ((object.ReferenceEquals(this.F_ISWJJField, value) != true)) {
                    this.F_ISWJJField = value;
                    this.RaisePropertyChanged("F_ISWJJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float F_KYLZ {
            get {
                return this.F_KYLZField;
            }
            set {
                if ((this.F_KYLZField.Equals(value) != true)) {
                    this.F_KYLZField = value;
                    this.RaisePropertyChanged("F_KYLZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int F_LQ {
            get {
                return this.F_LQField;
            }
            set {
                if ((this.F_LQField.Equals(value) != true)) {
                    this.F_LQField = value;
                    this.RaisePropertyChanged("F_LQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_OPERATOR {
            get {
                return this.F_OPERATORField;
            }
            set {
                if ((object.ReferenceEquals(this.F_OPERATORField, value) != true)) {
                    this.F_OPERATORField = value;
                    this.RaisePropertyChanged("F_OPERATOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_QDDJ {
            get {
                return this.F_QDDJField;
            }
            set {
                if ((object.ReferenceEquals(this.F_QDDJField, value) != true)) {
                    this.F_QDDJField = value;
                    this.RaisePropertyChanged("F_QDDJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_RTCODE {
            get {
                return this.F_RTCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.F_RTCODEField, value) != true)) {
                    this.F_RTCODEField = value;
                    this.RaisePropertyChanged("F_RTCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SBCODE {
            get {
                return this.F_SBCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SBCODEField, value) != true)) {
                    this.F_SBCODEField = value;
                    this.RaisePropertyChanged("F_SBCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SJBH {
            get {
                return this.F_SJBHField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SJBHField, value) != true)) {
                    this.F_SJBHField = value;
                    this.RaisePropertyChanged("F_SJBH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SJCC {
            get {
                return this.F_SJCCField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SJCCField, value) != true)) {
                    this.F_SJCCField = value;
                    this.RaisePropertyChanged("F_SJCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SOFTCOM {
            get {
                return this.F_SOFTCOMField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SOFTCOMField, value) != true)) {
                    this.F_SOFTCOMField = value;
                    this.RaisePropertyChanged("F_SOFTCOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SYSJ {
            get {
                return this.F_SYSJField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SYSJField, value) != true)) {
                    this.F_SYSJField = value;
                    this.RaisePropertyChanged("F_SYSJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_WTBH {
            get {
                return this.F_WTBHField;
            }
            set {
                if ((object.ReferenceEquals(this.F_WTBHField, value) != true)) {
                    this.F_WTBHField = value;
                    this.RaisePropertyChanged("F_WTBH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_YSKYLZ {
            get {
                return this.F_YSKYLZField;
            }
            set {
                if ((object.ReferenceEquals(this.F_YSKYLZField, value) != true)) {
                    this.F_YSKYLZField = value;
                    this.RaisePropertyChanged("F_YSKYLZ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversalData", Namespace="http://schemas.datacontract.org/2004/07/MixstationLibraryDMS.LabWCFService")]
    [System.SerializableAttribute()]
    public partial class UniversalData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float F_AREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_COLCOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float F_GCZJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float F_LZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_OPERATORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_PZCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float F_QFLZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_RTCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SBCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float F_SCLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SJBHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SOFTCOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_SYSJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_WTBHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_WYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_YSKLLZField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float F_AREA {
            get {
                return this.F_AREAField;
            }
            set {
                if ((this.F_AREAField.Equals(value) != true)) {
                    this.F_AREAField = value;
                    this.RaisePropertyChanged("F_AREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_COLCOM {
            get {
                return this.F_COLCOMField;
            }
            set {
                if ((object.ReferenceEquals(this.F_COLCOMField, value) != true)) {
                    this.F_COLCOMField = value;
                    this.RaisePropertyChanged("F_COLCOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float F_GCZJ {
            get {
                return this.F_GCZJField;
            }
            set {
                if ((this.F_GCZJField.Equals(value) != true)) {
                    this.F_GCZJField = value;
                    this.RaisePropertyChanged("F_GCZJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_GUID {
            get {
                return this.F_GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.F_GUIDField, value) != true)) {
                    this.F_GUIDField = value;
                    this.RaisePropertyChanged("F_GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float F_LZ {
            get {
                return this.F_LZField;
            }
            set {
                if ((this.F_LZField.Equals(value) != true)) {
                    this.F_LZField = value;
                    this.RaisePropertyChanged("F_LZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_OPERATOR {
            get {
                return this.F_OPERATORField;
            }
            set {
                if ((object.ReferenceEquals(this.F_OPERATORField, value) != true)) {
                    this.F_OPERATORField = value;
                    this.RaisePropertyChanged("F_OPERATOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_PZCODE {
            get {
                return this.F_PZCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.F_PZCODEField, value) != true)) {
                    this.F_PZCODEField = value;
                    this.RaisePropertyChanged("F_PZCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float F_QFLZ {
            get {
                return this.F_QFLZField;
            }
            set {
                if ((this.F_QFLZField.Equals(value) != true)) {
                    this.F_QFLZField = value;
                    this.RaisePropertyChanged("F_QFLZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_RTCODE {
            get {
                return this.F_RTCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.F_RTCODEField, value) != true)) {
                    this.F_RTCODEField = value;
                    this.RaisePropertyChanged("F_RTCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SBCODE {
            get {
                return this.F_SBCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SBCODEField, value) != true)) {
                    this.F_SBCODEField = value;
                    this.RaisePropertyChanged("F_SBCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float F_SCL {
            get {
                return this.F_SCLField;
            }
            set {
                if ((this.F_SCLField.Equals(value) != true)) {
                    this.F_SCLField = value;
                    this.RaisePropertyChanged("F_SCL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SJBH {
            get {
                return this.F_SJBHField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SJBHField, value) != true)) {
                    this.F_SJBHField = value;
                    this.RaisePropertyChanged("F_SJBH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SOFTCOM {
            get {
                return this.F_SOFTCOMField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SOFTCOMField, value) != true)) {
                    this.F_SOFTCOMField = value;
                    this.RaisePropertyChanged("F_SOFTCOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_SYSJ {
            get {
                return this.F_SYSJField;
            }
            set {
                if ((object.ReferenceEquals(this.F_SYSJField, value) != true)) {
                    this.F_SYSJField = value;
                    this.RaisePropertyChanged("F_SYSJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_WTBH {
            get {
                return this.F_WTBHField;
            }
            set {
                if ((object.ReferenceEquals(this.F_WTBHField, value) != true)) {
                    this.F_WTBHField = value;
                    this.RaisePropertyChanged("F_WTBH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_WY {
            get {
                return this.F_WYField;
            }
            set {
                if ((object.ReferenceEquals(this.F_WYField, value) != true)) {
                    this.F_WYField = value;
                    this.RaisePropertyChanged("F_WY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_YSKLLZ {
            get {
                return this.F_YSKLLZField;
            }
            set {
                if ((object.ReferenceEquals(this.F_YSKLLZField, value) != true)) {
                    this.F_YSKLLZField = value;
                    this.RaisePropertyChanged("F_YSKLLZ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabDocBasicInfo", Namespace="http://schemas.datacontract.org/2004/07/MixstationLibraryDMS.LabWCFService")]
    [System.SerializableAttribute()]
    public partial class LabDocBasicInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BGBHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBQUANTITYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBUNITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_VENDERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GGTYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISSUCCESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JLBHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOSUCCESSINFOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRJNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SBCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYJLXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYRERSONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYTYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WDMCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WTBHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WTDWField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BGBH {
            get {
                return this.BGBHField;
            }
            set {
                if ((object.ReferenceEquals(this.BGBHField, value) != true)) {
                    this.BGBHField = value;
                    this.RaisePropertyChanged("BGBH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBQUANTITY {
            get {
                return this.DBQUANTITYField;
            }
            set {
                if ((object.ReferenceEquals(this.DBQUANTITYField, value) != true)) {
                    this.DBQUANTITYField = value;
                    this.RaisePropertyChanged("DBQUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBUNIT {
            get {
                return this.DBUNITField;
            }
            set {
                if ((object.ReferenceEquals(this.DBUNITField, value) != true)) {
                    this.DBUNITField = value;
                    this.RaisePropertyChanged("DBUNIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_GUID {
            get {
                return this.F_GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.F_GUIDField, value) != true)) {
                    this.F_GUIDField = value;
                    this.RaisePropertyChanged("F_GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_VENDER {
            get {
                return this.F_VENDERField;
            }
            set {
                if ((object.ReferenceEquals(this.F_VENDERField, value) != true)) {
                    this.F_VENDERField = value;
                    this.RaisePropertyChanged("F_VENDER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GGTYPE {
            get {
                return this.GGTYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.GGTYPEField, value) != true)) {
                    this.GGTYPEField = value;
                    this.RaisePropertyChanged("GGTYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISSUCCESS {
            get {
                return this.ISSUCCESSField;
            }
            set {
                if ((object.ReferenceEquals(this.ISSUCCESSField, value) != true)) {
                    this.ISSUCCESSField = value;
                    this.RaisePropertyChanged("ISSUCCESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JLBH {
            get {
                return this.JLBHField;
            }
            set {
                if ((object.ReferenceEquals(this.JLBHField, value) != true)) {
                    this.JLBHField = value;
                    this.RaisePropertyChanged("JLBH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOSUCCESSINFO {
            get {
                return this.NOSUCCESSINFOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOSUCCESSINFOField, value) != true)) {
                    this.NOSUCCESSINFOField = value;
                    this.RaisePropertyChanged("NOSUCCESSINFO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRJNAME {
            get {
                return this.PRJNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.PRJNAMEField, value) != true)) {
                    this.PRJNAMEField = value;
                    this.RaisePropertyChanged("PRJNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SBCODE {
            get {
                return this.SBCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SBCODEField, value) != true)) {
                    this.SBCODEField = value;
                    this.RaisePropertyChanged("SBCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYDATE {
            get {
                return this.SYDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.SYDATEField, value) != true)) {
                    this.SYDATEField = value;
                    this.RaisePropertyChanged("SYDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYJLX {
            get {
                return this.SYJLXField;
            }
            set {
                if ((object.ReferenceEquals(this.SYJLXField, value) != true)) {
                    this.SYJLXField = value;
                    this.RaisePropertyChanged("SYJLX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYRERSON {
            get {
                return this.SYRERSONField;
            }
            set {
                if ((object.ReferenceEquals(this.SYRERSONField, value) != true)) {
                    this.SYRERSONField = value;
                    this.RaisePropertyChanged("SYRERSON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYTYPE {
            get {
                return this.SYTYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.SYTYPEField, value) != true)) {
                    this.SYTYPEField = value;
                    this.RaisePropertyChanged("SYTYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WDMC {
            get {
                return this.WDMCField;
            }
            set {
                if ((object.ReferenceEquals(this.WDMCField, value) != true)) {
                    this.WDMCField = value;
                    this.RaisePropertyChanged("WDMC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WTBH {
            get {
                return this.WTBHField;
            }
            set {
                if ((object.ReferenceEquals(this.WTBHField, value) != true)) {
                    this.WTBHField = value;
                    this.RaisePropertyChanged("WTBH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WTDW {
            get {
                return this.WTDWField;
            }
            set {
                if ((object.ReferenceEquals(this.WTDWField, value) != true)) {
                    this.WTDWField = value;
                    this.RaisePropertyChanged("WTDW");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LabMS.ILabManagerService")]
    public interface ILabManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadPressureData", ReplyAction="http://tempuri.org/ILabManagerService/UploadPressureDataResponse")]
        int UploadPressureData(out string errMsg, Yqun.BO.BusinessManager.LabMS.PressureData pressure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadUniversalData", ReplyAction="http://tempuri.org/ILabManagerService/UploadUniversalDataResponse")]
        int UploadUniversalData(out string errMsg, Yqun.BO.BusinessManager.LabMS.UniversalData universal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadLabDocBasicInfo", ReplyAction="http://tempuri.org/ILabManagerService/UploadLabDocBasicInfoResponse")]
        int UploadLabDocBasicInfo(out string errMsg, Yqun.BO.BusinessManager.LabMS.LabDocBasicInfo labdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadLabDocContent", ReplyAction="http://tempuri.org/ILabManagerService/UploadLabDocContentResponse")]
        int UploadLabDocContent(out string errMsg, string docContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/AuthentificationUser", ReplyAction="http://tempuri.org/ILabManagerService/AuthentificationUserResponse")]
        int AuthentificationUser(out string jsonUserinfo, out string errMsg, string sysbm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadPressureDataDES", ReplyAction="http://tempuri.org/ILabManagerService/UploadPressureDataDESResponse")]
        int UploadPressureDataDES(out string errMsg, string idcardnum, string d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadUniversalDataDES", ReplyAction="http://tempuri.org/ILabManagerService/UploadUniversalDataDESResponse")]
        int UploadUniversalDataDES(out string errMsg, string idcardnum, string jsonUniversal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadLabDocBasicInfoDES", ReplyAction="http://tempuri.org/ILabManagerService/UploadLabDocBasicInfoDESResponse")]
        int UploadLabDocBasicInfoDES(out string errMsg, string idcardnum, string jsonLabdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadLabDocContentDES", ReplyAction="http://tempuri.org/ILabManagerService/UploadLabDocContentDESResponse")]
        int UploadLabDocContentDES(out string errMsg, string idcardnum, string jsonLabDocContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/AuthentificationFile", ReplyAction="http://tempuri.org/ILabManagerService/AuthentificationFileResponse")]
        int AuthentificationFile(out string errMsg, string sbbh, string md5hash, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadLabMessage", ReplyAction="http://tempuri.org/ILabManagerService/UploadLabMessageResponse")]
        int UploadLabMessage(out string errMsg, Yqun.BO.BusinessManager.LabMS.LabDocBasicInfo labdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadLabMessageWeb", ReplyAction="http://tempuri.org/ILabManagerService/UploadLabMessageWebResponse")]
        int UploadLabMessageWeb(out string errMsg, Yqun.BO.BusinessManager.LabMS.LabDocBasicInfo labdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UploadLabStatus", ReplyAction="http://tempuri.org/ILabManagerService/UploadLabStatusResponse")]
        int UploadLabStatus(out string errMsg, string dmtype, string xlbh, string wtbh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/GetVenderCount", ReplyAction="http://tempuri.org/ILabManagerService/GetVenderCountResponse")]
        System.Data.DataSet GetVenderCount(int flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabManagerService/UpdateJgdmStatus", ReplyAction="http://tempuri.org/ILabManagerService/UpdateJgdmStatusResponse")]
        int UpdateJgdmStatus(string sbbh, int result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ILabManagerServiceChannel : Yqun.BO.BusinessManager.LabMS.ILabManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LabManagerServiceClient : System.ServiceModel.ClientBase<Yqun.BO.BusinessManager.LabMS.ILabManagerService>, Yqun.BO.BusinessManager.LabMS.ILabManagerService {
        
        public LabManagerServiceClient() {
        }
        
        public LabManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UploadPressureData(out string errMsg, Yqun.BO.BusinessManager.LabMS.PressureData pressure) {
            return base.Channel.UploadPressureData(out errMsg, pressure);
        }
        
        public int UploadUniversalData(out string errMsg, Yqun.BO.BusinessManager.LabMS.UniversalData universal) {
            return base.Channel.UploadUniversalData(out errMsg, universal);
        }
        
        public int UploadLabDocBasicInfo(out string errMsg, Yqun.BO.BusinessManager.LabMS.LabDocBasicInfo labdata) {
            return base.Channel.UploadLabDocBasicInfo(out errMsg, labdata);
        }
        
        public int UploadLabDocContent(out string errMsg, string docContext) {
            return base.Channel.UploadLabDocContent(out errMsg, docContext);
        }
        
        public int AuthentificationUser(out string jsonUserinfo, out string errMsg, string sysbm) {
            return base.Channel.AuthentificationUser(out jsonUserinfo, out errMsg, sysbm);
        }
        
        public int UploadPressureDataDES(out string errMsg, string idcardnum, string d) {
            return base.Channel.UploadPressureDataDES(out errMsg, idcardnum, d);
        }
        
        public int UploadUniversalDataDES(out string errMsg, string idcardnum, string jsonUniversal) {
            return base.Channel.UploadUniversalDataDES(out errMsg, idcardnum, jsonUniversal);
        }
        
        public int UploadLabDocBasicInfoDES(out string errMsg, string idcardnum, string jsonLabdata) {
            return base.Channel.UploadLabDocBasicInfoDES(out errMsg, idcardnum, jsonLabdata);
        }
        
        public int UploadLabDocContentDES(out string errMsg, string idcardnum, string jsonLabDocContent) {
            return base.Channel.UploadLabDocContentDES(out errMsg, idcardnum, jsonLabDocContent);
        }
        
        public int AuthentificationFile(out string errMsg, string sbbh, string md5hash, string path) {
            return base.Channel.AuthentificationFile(out errMsg, sbbh, md5hash, path);
        }
        
        public int UploadLabMessage(out string errMsg, Yqun.BO.BusinessManager.LabMS.LabDocBasicInfo labdata) {
            return base.Channel.UploadLabMessage(out errMsg, labdata);
        }
        
        public int UploadLabMessageWeb(out string errMsg, Yqun.BO.BusinessManager.LabMS.LabDocBasicInfo labdata) {
            return base.Channel.UploadLabMessageWeb(out errMsg, labdata);
        }
        
        public int UploadLabStatus(out string errMsg, string dmtype, string xlbh, string wtbh) {
            return base.Channel.UploadLabStatus(out errMsg, dmtype, xlbh, wtbh);
        }
        
        public System.Data.DataSet GetVenderCount(int flag) {
            return base.Channel.GetVenderCount(flag);
        }
        
        public int UpdateJgdmStatus(string sbbh, int result) {
            return base.Channel.UpdateJgdmStatus(sbbh, result);
        }
    }
}
